version: '3'

services:
  node-reign:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: reign-challenge-docker
    container_name: node-reign
    restart: always # Restart if container stops
    ports:
      - "${PORT_SV}:${PORT_SV}"
    environment:
      MONGODB: ${MONGODB}
      PORT_SV: ${PORT_SV}
      PORT_DB: ${PORT_DB}


  db:
    image: mongo:5
    container_name: mongo-reign
    restart: always
    ports:
      - "${PORT_DB}:${PORT_DB}"
    environment:
      MONGODB_DATABASE: reign-challenge
    volumes:
      - ./mongo:/data/db